[package]
name = "mangameeya"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
eframe.workspace = true
egui.workspace = true
mm-archive.workspace = true
mm-image.workspace = true
mm-core.workspace = true
mm-config.workspace = true
rfd = "0.15"
arboard = "3"
image = { workspace = true }
