[package]
name = "mm-archive"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
rayon.workspace = true
zip.workspace = true
tracing.workspace = true
tar = "0.4"
flate2 = "1"

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
tempfile = "3"
image.workspace = true

[[bench]]
name = "archive_bench"
harness = false
